export const CATEGORIAS = [
    { id: 'Kits e Combos', icon: null, i: '0' },
    { id: 'SmartWatchs', icon: null , i: '1'},
    { id: 'Caixas de som', icon: null , i: '2'},
    { id: 'Eletronicos', icon: null, i: '3' },
    { id: 'Maquina de cabelo', icon: null, i: '4' },
    { id: 'Automotivos', icon: null, i: '5' },
    { id: 'Video Game', icon: null, i: '6' },
    { id: 'Computador', icon: null, i: '7' },
    { id: 'Ferramentas', icon: null, i: '8' },
    { id: 'Brinquedos', icon: null, i: '9' },
    { id: 'Relogios', icon: null, i: '10' },
    { id: 'Headset e Fones', icon: null, i: '11' },
    { id: 'Luz e Iluminação', icon: null, i: '12' },
    { id: 'Câmeras', icon: null, i: '13' },
    { id: 'Oculos', icon: null, i: '14' },
    { id: 'Celulares e Acss', icon: null, i: '15' },
    { id: 'Audio e Som', icon: null, i: '30' },
    { id: 'Piscinas', icon: null, i: '17' },
    { id: 'Microfones', icon: null, i: '18' },
    { id: 'Petshop', icon: null, i: '19' },
    { id: 'Tv e acessorios', icon: null, i: '20' },
    { id: 'Cabos', icon: null, i: '21' },
    { id: 'Inversores', icon: null, i: '43' },
    { id: 'Malas e Bolsas', icon: null, i: '35' },
    { id: 'Ventiladores', icon: null, i: '48' },
    { id: 'Panelas', icon: null, i: '50' },
];